name: Testes E2E com Cypress e Publicação de Resultados

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  run-cypress-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes E2E com Cypress
        uses: cypress-io/github-action@v6
        with:
          browser: chrome

      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v4
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./public